config/routes.rb
Rails.application.routes.draw do
  resources :konfirmasis
  resources :homeitems
  resources :statics
  resources :feedbacks
  resources :statuses
  resources :carts
  resources :favorite_produks
  resources :subcategories
  resources :categories
  resources :produks
  resources :tokos
  resources :rekenings
  resources :alamats
  resources :pets

  root 'home#index'
  get "/formkonfirmasi/:id" => "home#formkonfirmasi"
  get "/hitungongkir" => "produks#hitungongkir"
  get "/display" => "home#display"
  get "/tentang" => "home#tentang"
  get "/karir" => "home#karir"
  get "/tokos/:id/review" => "tokos#review"
  get "/alamats/new/:provinsi" => "alamats#new"
  get "/alamats/new/:provinsi/:kota" => "alamats#new"
  get "/tokos/new/:provinsi" => "tokos#new"
  get "/tokos/new/:provinsi/:kota" => "tokos#new"
  get "/alamats/edit/:id/:provinsi" => "alamats#edit"
  get "/alamats/edit/:id/:provinsi/:kota" => "alamats#edit"
  get "/tokos/:id/edit/:provinsi" => "tokos#edit"
  get "/tokos/:id/edit/:provinsi/:kota" => "tokos#edit"
  get "/email" => "home#email"
  get "/cari" => "produks#cari"
  get "/checkout" => "carts#checkout"
  get "/konfirmasi-pengiriman/:id/:resi" => "carts#kirim_pesanan"
  get "/pengiriman-sampai/:id" => "carts#pesanan_sampai"
  get "/terima-pesanan/:id" => "carts#terima_pesanan"
  get "/tolak-pesanan/:id" => "carts#tolak_pesanan"
  get "/diterima" => "carts#diterima"
  get "/konfirmasi-pembayaran" => "home#konfirmasi-pembayaran"
  get "/payment" => "home#payment"
  get "/konfirmasi-pengiriman" => "home#konfirmasi-pengiriman"
  get "/daftar-penjualan" => "home#daftar-penjualan"
  get "/pesanan-baru" => "home#pesanan-baru"
  get "/daftar-transaksi" => "home#daftar-transaksi"
  get "/konfirmasi-penerimaan" => "home#konfirmasi-penerimaan"
  get "/status-pemesanan" => "home#status-pemesanan"
  get "/berhasil" => "home#confirmed"
  get "/bayar" => "home#bayar"
  get "/wishlist" => "home#wishlist"
  get "/profil" => "home#profil"
  get "/finish" => "home#finish"
  get "/masuk" => "home#masuk"
  get "/konfirmasi" => "home#konfirmasi"
  get "/terms" => "home#terms"
  get "/kategori" => "tokos#kategori"
  get "/pengiriman/:id" => "tokos#pengiriman"
  get "/produks/:id/unfav" => "favorite_produks#destroy"

  get 'admin/terimakonfirmasi/:id/:konfirmasi_id' => "admins#terimakonfirmasi"
  get 'admin/tolakkonfirmasi/:id/:konfirmasi_id' => "admins#tolakkonfirmasi"
  get 'admin/konfirmasi/:id' => "admins#konfirmasi"
  get 'admin/konfirmasi' => "admins#konfirmasi"
  get 'admin/beadmin/:id' => "admins#becomeadmin"
  get 'admin/deladmin/:id' => "admins#deleteadmin"
  get 'admin/users' => "admins#users"
  get 'admin/edituser/:id' => "admins#users"
  post 'admin/edituser/:id' => "admins#users"
  get 'admin/homepage' => "admins#homepage"
  get 'admin/homepage/:id' => "admins#homepage"
  get 'admin/stores' => "admins#stores"
  get 'admin/stores/:id' => "admins#stores"
  get 'admin/products' => "admins#products"
  get 'admin/products/:id' => "admins#products"
  get 'admin/categories' => "admins#categories"
  get 'admin/categories/new' => "admins#newcategory"
  get 'admin/categories/:id' => "admins#categories"
  get 'admin/subcategories' => "admins#subcategories"
  get 'admin/subcategories/:id' => "admins#subcategories"
  get 'admin/statics' => "admins#statics"
  get 'admin/statics/:id' => "admins#statics"
  get 'admin' => "admins#dashboard"

  match 'deleteuser/:id' => 'admins#destroyuser', :via => :delete, :as => :admin_destroy_user
  match 'deletestore/:id' => 'admins#destroystore', :via => :delete, :as => :admin_destroy_store
  match 'deleteproduct/:id' => 'admins#destroyproduct', :via => :delete, :as => :admin_destroy_product
  match 'deletecategory/:id' => 'admins#destroycategory', :via => :delete, :as => :admin_destroy_category
  match 'deletesubcategory/:id' => 'admins#destroysubcategory', :via => :delete, :as => :admin_destroy_subcategory
  match 'deletestatic/:id' => 'admins#destroystatic', :via => :delete, :as => :admin_destroy_static

  devise_scope :user do
    get "/daftar" => "devise/registrations#new"
    get "/editprofil" => "user/registrations#edit"
  end

  devise_for :users, controllers: {
  confirmations: "users/confirmations",
  passwords: "users/passwords",
  registrations: "users/registrations",
  sessions: "users/sessions",
  unlocks: "users/unlocks",
  update: "/profil",
  }, :path => '', :path_names => {:sign_in => 'masuk', :sign_out => 'logout'}

end

app/models/homeitem.rb
class Homeitem < ActiveRecord::Base
  mount_uploader :img1, ImageUploader
  mount_uploader :img2, ImageUploader
  mount_uploader :img3, ImageUploader
  mount_uploader :img4, ImageUploader
  mount_uploader :img5, ImageUploader
  mount_uploader :img6, ImageUploader
  mount_uploader :img7, ImageUploader
  mount_uploader :img8, ImageUploader
  mount_uploader :img9, ImageUploader
end

app/controllers/homeitems_controller.rb
class HomeitemsController < ApplicationController
  before_action :set_homeitem, only: [:show, :edit, :update, :destroy]

  # GET /homeitems
  # GET /homeitems.json
  def index
    @homeitems = Homeitem.all
  end

  # GET /homeitems/1
  # GET /homeitems/1.json
  def show
  end

  # GET /homeitems/new
  def new
    @homeitem = Homeitem.new
  end

  # GET /homeitems/1/edit
  def edit
  end

  # POST /homeitems
  # POST /homeitems.json
  def create
    @homeitem = Homeitem.new(homeitem_params)

    respond_to do |format|
      if @homeitem.save
        format.html { redirect_to :back, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @homeitem }
      else
        format.html { render :new }
        format.json { render json: @homeitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homeitems/1
  # PATCH/PUT /homeitems/1.json
  def update
    respond_to do |format|
      if @homeitem.update(homeitem_params)
        format.html { redirect_to :back, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @homeitem }
      else
        format.html { render :edit }
        format.json { render json: @homeitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homeitems/1
  # DELETE /homeitems/1.json
  def destroy
    @homeitem.destroy
    respond_to do |format|
      format.html { redirect_to homeitems_url, notice: 'Homeitem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_homeitem
      @homeitem = Homeitem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def homeitem_params
      params.require(:homeitem).permit(:title, :description, :img1, :img2, :img3, :img4, :img5, :img6, :img7, :img8, :img9, :remove_img1, :remove_img2, :remove_img3, :remove_img4, :remove_img5, :remove_img6, :remove_img7, :remove_img8, :remove_img9)
    end
end

app/helpers/homeitems_helper.rb
module HomeitemsHelper
end

app/views/homeitems/_form.html.erb
<%= form_for(@homeitem) do |f| %>
  <% if @homeitem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@homeitem.errors.count, "error") %> prohibited this homeitem from being saved:</h2>

      <ul>
      <% @homeitem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :img1 %><br>
    <%= f.text_field :img1 %>
  </div>
  <div class="field">
    <%= f.label :img2 %><br>
    <%= f.text_field :img2 %>
  </div>
  <div class="field">
    <%= f.label :img3 %><br>
    <%= f.text_field :img3 %>
  </div>
  <div class="field">
    <%= f.label :img4 %><br>
    <%= f.text_field :img4 %>
  </div>
  <div class="field">
    <%= f.label :img5 %><br>
    <%= f.text_field :img5 %>
  </div>
  <div class="field">
    <%= f.label :img6 %><br>
    <%= f.text_field :img6 %>
  </div>
  <div class="field">
    <%= f.label :img7 %><br>
    <%= f.text_field :img7 %>
  </div>
  <div class="field">
    <%= f.label :img8 %><br>
    <%= f.text_field :img8 %>
  </div>
  <div class="field">
    <%= f.label :img9 %><br>
    <%= f.text_field :img9 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homeitems/edit.html.erb
<h1>Editing Homeitem</h1>

<%= render 'form' %>

<%= link_to 'Show', @homeitem %> |
<%= link_to 'Back', homeitems_path %>

app/views/homeitems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Homeitems</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Img1</th>
      <th>Img2</th>
      <th>Img3</th>
      <th>Img4</th>
      <th>Img5</th>
      <th>Img6</th>
      <th>Img7</th>
      <th>Img8</th>
      <th>Img9</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @homeitems.each do |homeitem| %>
      <tr>
        <td><%= homeitem.title %></td>
        <td><%= homeitem.description %></td>
        <td><%= homeitem.img1 %></td>
        <td><%= homeitem.img2 %></td>
        <td><%= homeitem.img3 %></td>
        <td><%= homeitem.img4 %></td>
        <td><%= homeitem.img5 %></td>
        <td><%= homeitem.img6 %></td>
        <td><%= homeitem.img7 %></td>
        <td><%= homeitem.img8 %></td>
        <td><%= homeitem.img9 %></td>
        <td><%= link_to 'Show', homeitem %></td>
        <td><%= link_to 'Edit', edit_homeitem_path(homeitem) %></td>
        <td><%= link_to 'Destroy', homeitem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Homeitem', new_homeitem_path %>

app/views/homeitems/new.html.erb
<h1>New Homeitem</h1>

<%= render 'form' %>

<%= link_to 'Back', homeitems_path %>

app/views/homeitems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @homeitem.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @homeitem.description %>
</p>

<p>
  <strong>Img1:</strong>
  <%= @homeitem.img1 %>
</p>

<p>
  <strong>Img2:</strong>
  <%= @homeitem.img2 %>
</p>

<p>
  <strong>Img3:</strong>
  <%= @homeitem.img3 %>
</p>

<p>
  <strong>Img4:</strong>
  <%= @homeitem.img4 %>
</p>

<p>
  <strong>Img5:</strong>
  <%= @homeitem.img5 %>
</p>

<p>
  <strong>Img6:</strong>
  <%= @homeitem.img6 %>
</p>

<p>
  <strong>Img7:</strong>
  <%= @homeitem.img7 %>
</p>

<p>
  <strong>Img8:</strong>
  <%= @homeitem.img8 %>
</p>

<p>
  <strong>Img9:</strong>
  <%= @homeitem.img9 %>
</p>

<%= link_to 'Edit', edit_homeitem_path(@homeitem) %> |
<%= link_to 'Back', homeitems_path %>