config/routes.rb
Rails.application.routes.draw do
  resources :konfirmasis
  resources :homeitems
  resources :statics
  resources :feedbacks
  resources :statuses
  resources :carts
  resources :favorite_produks
  resources :subcategories
  resources :categories
  resources :produks
  resources :tokos
  resources :rekenings
  resources :alamats
  resources :pets

  root 'home#index'
  get "/formkonfirmasi/:id" => "home#formkonfirmasi"
  get "/hitungongkir" => "produks#hitungongkir"
  get "/display" => "home#display"
  get "/tentang" => "home#tentang"
  get "/karir" => "home#karir"
  get "/tokos/:id/review" => "tokos#review"
  get "/alamats/new/:provinsi" => "alamats#new"
  get "/alamats/new/:provinsi/:kota" => "alamats#new"
  get "/tokos/new/:provinsi" => "tokos#new"
  get "/tokos/new/:provinsi/:kota" => "tokos#new"
  get "/alamats/edit/:id/:provinsi" => "alamats#edit"
  get "/alamats/edit/:id/:provinsi/:kota" => "alamats#edit"
  get "/tokos/:id/edit/:provinsi" => "tokos#edit"
  get "/tokos/:id/edit/:provinsi/:kota" => "tokos#edit"
  get "/email" => "home#email"
  get "/cari" => "produks#cari"
  get "/checkout" => "carts#checkout"
  get "/konfirmasi-pengiriman/:id/:resi" => "carts#kirim_pesanan"
  get "/pengiriman-sampai/:id" => "carts#pesanan_sampai"
  get "/terima-pesanan/:id" => "carts#terima_pesanan"
  get "/tolak-pesanan/:id" => "carts#tolak_pesanan"
  get "/diterima" => "carts#diterima"
  get "/konfirmasi-pembayaran" => "home#konfirmasi-pembayaran"
  get "/payment" => "home#payment"
  get "/konfirmasi-pengiriman" => "home#konfirmasi-pengiriman"
  get "/daftar-penjualan" => "home#daftar-penjualan"
  get "/pesanan-baru" => "home#pesanan-baru"
  get "/daftar-transaksi" => "home#daftar-transaksi"
  get "/konfirmasi-penerimaan" => "home#konfirmasi-penerimaan"
  get "/status-pemesanan" => "home#status-pemesanan"
  get "/berhasil" => "home#confirmed"
  get "/bayar" => "home#bayar"
  get "/wishlist" => "home#wishlist"
  get "/profil" => "home#profil"
  get "/finish" => "home#finish"
  get "/masuk" => "home#masuk"
  get "/konfirmasi" => "home#konfirmasi"
  get "/terms" => "home#terms"
  get "/kategori" => "tokos#kategori"
  get "/pengiriman/:id" => "tokos#pengiriman"
  get "/produks/:id/unfav" => "favorite_produks#destroy"

  get 'admin/terimakonfirmasi/:id/:konfirmasi_id' => "admins#terimakonfirmasi"
  get 'admin/tolakkonfirmasi/:id/:konfirmasi_id' => "admins#tolakkonfirmasi"
  get 'admin/konfirmasi/:id' => "admins#konfirmasi"
  get 'admin/konfirmasi' => "admins#konfirmasi"
  get 'admin/beadmin/:id' => "admins#becomeadmin"
  get 'admin/deladmin/:id' => "admins#deleteadmin"
  get 'admin/users' => "admins#users"
  get 'admin/edituser/:id' => "admins#users"
  post 'admin/edituser/:id' => "admins#users"
  get 'admin/homepage' => "admins#homepage"
  get 'admin/homepage/:id' => "admins#homepage"
  get 'admin/stores' => "admins#stores"
  get 'admin/stores/:id' => "admins#stores"
  get 'admin/products' => "admins#products"
  get 'admin/products/:id' => "admins#products"
  get 'admin/categories' => "admins#categories"
  get 'admin/categories/new' => "admins#newcategory"
  get 'admin/categories/:id' => "admins#categories"
  get 'admin/subcategories' => "admins#subcategories"
  get 'admin/subcategories/:id' => "admins#subcategories"
  get 'admin/statics' => "admins#statics"
  get 'admin/statics/:id' => "admins#statics"
  get 'admin' => "admins#dashboard"

  match 'deleteuser/:id' => 'admins#destroyuser', :via => :delete, :as => :admin_destroy_user
  match 'deletestore/:id' => 'admins#destroystore', :via => :delete, :as => :admin_destroy_store
  match 'deleteproduct/:id' => 'admins#destroyproduct', :via => :delete, :as => :admin_destroy_product
  match 'deletecategory/:id' => 'admins#destroycategory', :via => :delete, :as => :admin_destroy_category
  match 'deletesubcategory/:id' => 'admins#destroysubcategory', :via => :delete, :as => :admin_destroy_subcategory
  match 'deletestatic/:id' => 'admins#destroystatic', :via => :delete, :as => :admin_destroy_static

  devise_scope :user do
    get "/daftar" => "devise/registrations#new"
    get "/editprofil" => "user/registrations#edit"
  end

  devise_for :users, controllers: {
  confirmations: "users/confirmations",
  passwords: "users/passwords",
  registrations: "users/registrations",
  sessions: "users/sessions",
  unlocks: "users/unlocks",
  update: "/profil",
  }, :path => '', :path_names => {:sign_in => 'masuk', :sign_out => 'logout'}

end

app/models/static.rb
class Static < ActiveRecord::Base
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  before_action :set_static, only: [:show, :edit, :update, :destroy]

  # GET /statics
  # GET /statics.json
  def index
    @statics = Static.all
  end

  # GET /statics/1
  # GET /statics/1.json
  def show
  end

  # GET /statics/new
  def new
    @static = Static.new
  end

  # GET /statics/1/edit
  def edit
  end

  # POST /statics
  # POST /statics.json
  def create
    @static = Static.new(static_params)

    respond_to do |format|
      if @static.save
        format.html { redirect_to :back, notice: 'Halaman telah dibuat.' }
        format.json { render :show, status: :created, location: @static }
      else
        format.html { render :new }
        format.json { render json: @static.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statics/1
  # PATCH/PUT /statics/1.json
  def update
    respond_to do |format|
      if @static.update(static_params)
        format.html { redirect_to :back, notice: 'Halaman diperbarui' }
        format.json { render :show, status: :ok, location: @static }
      else
        format.html { render :edit }
        format.json { render json: @static.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statics/1
  # DELETE /statics/1.json
  def destroy
    @static.destroy
    respond_to do |format|
      format.html { redirect_to statics_url, notice: 'Halaman dihapus' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_static
      @static = Static.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def static_params
      params.require(:static).permit(:title, :body, :image)
    end
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/statics/_form.html.erb
<%= form_for(@static) do |f| %>
  <% if @static.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@static.errors.count, "error") %> prohibited this static from being saved:</h2>

      <ul>
      <% @static.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statics/edit.html.erb
<h1>Editing Static</h1>

<%= render 'form' %>

<%= link_to 'Show', @static %> |
<%= link_to 'Back', statics_path %>

app/views/statics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Statics</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @statics.each do |static| %>
      <tr>
        <td><%= static.title %></td>
        <td><%= static.body %></td>
        <td><%= static.image %></td>
        <td><%= link_to 'Show', static %></td>
        <td><%= link_to 'Edit', edit_static_path(static) %></td>
        <td><%= link_to 'Destroy', static, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Static', new_static_path %>

app/views/statics/new.html.erb
<h1>New Static</h1>

<%= render 'form' %>

<%= link_to 'Back', statics_path %>

app/views/statics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @static.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @static.body %>
</p>

<p>
  <strong>Image:</strong>
  <%= @static.image %>
</p>

<%= link_to 'Edit', edit_static_path(@static) %> |
<%= link_to 'Back', statics_path %>