config/routes.rb
Rails.application.routes.draw do
  resources :konfirmasis
  resources :homeitems
  resources :statics
  resources :feedbacks
  resources :statuses
  resources :carts
  resources :favorite_produks
  resources :subcategories
  resources :categories
  resources :produks
  resources :tokos
  resources :rekenings
  resources :alamats
  resources :pets

  root 'home#index'
  get "/formkonfirmasi/:id" => "home#formkonfirmasi"
  get "/hitungongkir" => "produks#hitungongkir"
  get "/display" => "home#display"
  get "/tentang" => "home#tentang"
  get "/karir" => "home#karir"
  get "/tokos/:id/review" => "tokos#review"
  get "/alamats/new/:provinsi" => "alamats#new"
  get "/alamats/new/:provinsi/:kota" => "alamats#new"
  get "/tokos/new/:provinsi" => "tokos#new"
  get "/tokos/new/:provinsi/:kota" => "tokos#new"
  get "/alamats/edit/:id/:provinsi" => "alamats#edit"
  get "/alamats/edit/:id/:provinsi/:kota" => "alamats#edit"
  get "/tokos/:id/edit/:provinsi" => "tokos#edit"
  get "/tokos/:id/edit/:provinsi/:kota" => "tokos#edit"
  get "/email" => "home#email"
  get "/cari" => "produks#cari"
  get "/checkout" => "carts#checkout"
  get "/konfirmasi-pengiriman/:id/:resi" => "carts#kirim_pesanan"
  get "/pengiriman-sampai/:id" => "carts#pesanan_sampai"
  get "/terima-pesanan/:id" => "carts#terima_pesanan"
  get "/tolak-pesanan/:id" => "carts#tolak_pesanan"
  get "/diterima" => "carts#diterima"
  get "/konfirmasi-pembayaran" => "home#konfirmasi-pembayaran"
  get "/payment" => "home#payment"
  get "/konfirmasi-pengiriman" => "home#konfirmasi-pengiriman"
  get "/daftar-penjualan" => "home#daftar-penjualan"
  get "/pesanan-baru" => "home#pesanan-baru"
  get "/daftar-transaksi" => "home#daftar-transaksi"
  get "/konfirmasi-penerimaan" => "home#konfirmasi-penerimaan"
  get "/status-pemesanan" => "home#status-pemesanan"
  get "/berhasil" => "home#confirmed"
  get "/bayar" => "home#bayar"
  get "/wishlist" => "home#wishlist"
  get "/profil" => "home#profil"
  get "/finish" => "home#finish"
  get "/masuk" => "home#masuk"
  get "/konfirmasi" => "home#konfirmasi"
  get "/terms" => "home#terms"
  get "/kategori" => "tokos#kategori"
  get "/pengiriman/:id" => "tokos#pengiriman"
  get "/produks/:id/unfav" => "favorite_produks#destroy"

  get 'admin/terimakonfirmasi/:id/:konfirmasi_id' => "admins#terimakonfirmasi"
  get 'admin/tolakkonfirmasi/:id/:konfirmasi_id' => "admins#tolakkonfirmasi"
  get 'admin/konfirmasi/:id' => "admins#konfirmasi"
  get 'admin/konfirmasi' => "admins#konfirmasi"
  get 'admin/beadmin/:id' => "admins#becomeadmin"
  get 'admin/deladmin/:id' => "admins#deleteadmin"
  get 'admin/users' => "admins#users"
  get 'admin/edituser/:id' => "admins#users"
  post 'admin/edituser/:id' => "admins#users"
  get 'admin/homepage' => "admins#homepage"
  get 'admin/homepage/:id' => "admins#homepage"
  get 'admin/stores' => "admins#stores"
  get 'admin/stores/:id' => "admins#stores"
  get 'admin/products' => "admins#products"
  get 'admin/products/:id' => "admins#products"
  get 'admin/categories' => "admins#categories"
  get 'admin/categories/new' => "admins#newcategory"
  get 'admin/categories/:id' => "admins#categories"
  get 'admin/subcategories' => "admins#subcategories"
  get 'admin/subcategories/:id' => "admins#subcategories"
  get 'admin/statics' => "admins#statics"
  get 'admin/statics/:id' => "admins#statics"
  get 'admin' => "admins#dashboard"

  match 'deleteuser/:id' => 'admins#destroyuser', :via => :delete, :as => :admin_destroy_user
  match 'deletestore/:id' => 'admins#destroystore', :via => :delete, :as => :admin_destroy_store
  match 'deleteproduct/:id' => 'admins#destroyproduct', :via => :delete, :as => :admin_destroy_product
  match 'deletecategory/:id' => 'admins#destroycategory', :via => :delete, :as => :admin_destroy_category
  match 'deletesubcategory/:id' => 'admins#destroysubcategory', :via => :delete, :as => :admin_destroy_subcategory
  match 'deletestatic/:id' => 'admins#destroystatic', :via => :delete, :as => :admin_destroy_static

  devise_scope :user do
    get "/daftar" => "devise/registrations#new"
    get "/editprofil" => "user/registrations#edit"
  end

  devise_for :users, controllers: {
  confirmations: "users/confirmations",
  passwords: "users/passwords",
  registrations: "users/registrations",
  sessions: "users/sessions",
  unlocks: "users/unlocks",
  update: "/profil",
  }, :path => '', :path_names => {:sign_in => 'masuk', :sign_out => 'logout'}

end

app/models/konfirmasi.rb
class Konfirmasi < ActiveRecord::Base
  belongs_to :cart
  belongs_to :user
end

app/controllers/konfirmasis_controller.rb
class KonfirmasisController < ApplicationController
  before_action :set_konfirmasi, only: [:show, :edit, :update, :destroy]

  # GET /konfirmasis
  # GET /konfirmasis.json
  def index
    @konfirmasis = Konfirmasi.all
  end

  # GET /konfirmasis/1
  # GET /konfirmasis/1.json
  def show
  end

  # GET /konfirmasis/new
  def new
    @konfirmasi = Konfirmasi.new
  end

  # GET /konfirmasis/1/edit
  def edit
  end

  # POST /konfirmasis
  # POST /konfirmasis.json
  def create
    Cart.find(params[:cart_id]).update(:state => 3)
    mycart = Cart.find(params[:cart_id])
    status = "Telah Dikonfirmasi Buyer"
    Notifikasi.sample_email(current_user, mycart, status).deliver_later
    @konfirmasi = Konfirmasi.new(konfirmasi_params)
    @konfirmasi.user_id = current_user.id

    respond_to do |format|
      if @konfirmasi.save
        format.html { redirect_to "/konfirmasi-pembayaran", notice: 'Konfirmasi telah terkirim.' }
        format.json { render :show, status: :created, location: @konfirmasi }
      else
        format.html { render :new }
        format.json { render json: @konfirmasi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /konfirmasis/1
  # PATCH/PUT /konfirmasis/1.json
  def update
    respond_to do |format|
      if @konfirmasi.update(konfirmasi_params)
        format.html { redirect_to @konfirmasi, notice: 'Konfirmasi was successfully updated.' }
        format.json { render :show, status: :ok, location: @konfirmasi }
      else
        format.html { render :edit }
        format.json { render json: @konfirmasi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /konfirmasis/1
  # DELETE /konfirmasis/1.json
  def destroy
    @konfirmasi.destroy
    respond_to do |format|
      format.html { redirect_to konfirmasis_url, notice: 'Konfirmasi was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_konfirmasi
      @konfirmasi = Konfirmasi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def konfirmasi_params
      params.require(:konfirmasi).permit(:user_id, :cart_id, :tanggal, :bulan, :tahun, :metode, :dari, :tujuan, :keterangan, :jumlah)
    end
end

app/helpers/konfirmasis_helper.rb
module KonfirmasisHelper
end

app/views/konfirmasis/_form.html.erb
<%= form_for(@konfirmasi) do |f| %>
  <% if @konfirmasi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@konfirmasi.errors.count, "error") %> prohibited this konfirmasi from being saved:</h2>

      <ul>
      <% @konfirmasi.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.number_field :cart_id %>
  </div>
  <div class="field">
    <%= f.label :tanggal %><br>
    <%= f.text_field :tanggal %>
  </div>
  <div class="field">
    <%= f.label :bulan %><br>
    <%= f.text_field :bulan %>
  </div>
  <div class="field">
    <%= f.label :tahun %><br>
    <%= f.text_field :tahun %>
  </div>
  <div class="field">
    <%= f.label :metode %><br>
    <%= f.text_field :metode %>
  </div>
  <div class="field">
    <%= f.label :dari %><br>
    <%= f.text_field :dari %>
  </div>
  <div class="field">
    <%= f.label :tujuan %><br>
    <%= f.text_field :tujuan %>
  </div>
  <div class="field">
    <%= f.label :keterangan %><br>
    <%= f.text_field :keterangan %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/konfirmasis/edit.html.erb
<h1>Editing Konfirmasi</h1>

<%= render 'form' %>

<%= link_to 'Show', @konfirmasi %> |
<%= link_to 'Back', konfirmasis_path %>

app/views/konfirmasis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Konfirmasis</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Cart</th>
      <th>Tanggal</th>
      <th>Bulan</th>
      <th>Tahun</th>
      <th>Metode</th>
      <th>Dari</th>
      <th>Tujuan</th>
      <th>Keterangan</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @konfirmasis.each do |konfirmasi| %>
      <tr>
        <td><%= konfirmasi.user_id %></td>
        <td><%= konfirmasi.cart_id %></td>
        <td><%= konfirmasi.tanggal %></td>
        <td><%= konfirmasi.bulan %></td>
        <td><%= konfirmasi.tahun %></td>
        <td><%= konfirmasi.metode %></td>
        <td><%= konfirmasi.dari %></td>
        <td><%= konfirmasi.tujuan %></td>
        <td><%= konfirmasi.keterangan %></td>
        <td><%= link_to 'Show', konfirmasi %></td>
        <td><%= link_to 'Edit', edit_konfirmasi_path(konfirmasi) %></td>
        <td><%= link_to 'Destroy', konfirmasi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Konfirmasi', new_konfirmasi_path %>

app/views/konfirmasis/new.html.erb
<h1>New Konfirmasi</h1>

<%= render 'form' %>

<%= link_to 'Back', konfirmasis_path %>

app/views/konfirmasis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @konfirmasi.user_id %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @konfirmasi.cart_id %>
</p>

<p>
  <strong>Tanggal:</strong>
  <%= @konfirmasi.tanggal %>
</p>

<p>
  <strong>Bulan:</strong>
  <%= @konfirmasi.bulan %>
</p>

<p>
  <strong>Tahun:</strong>
  <%= @konfirmasi.tahun %>
</p>

<p>
  <strong>Metode:</strong>
  <%= @konfirmasi.metode %>
</p>

<p>
  <strong>Dari:</strong>
  <%= @konfirmasi.dari %>
</p>

<p>
  <strong>Tujuan:</strong>
  <%= @konfirmasi.tujuan %>
</p>

<p>
  <strong>Keterangan:</strong>
  <%= @konfirmasi.keterangan %>
</p>

<%= link_to 'Edit', edit_konfirmasi_path(@konfirmasi) %> |
<%= link_to 'Back', konfirmasis_path %>